import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'
import { Web3AuthProvider } from '@/services/web3auth'

export default function Home() {

  const App = dynamic(
    () => {
      return import("./App");
    },
    { ssr: false }
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Web3AuthProvider>
            <App />
          </Web3AuthProvider>
        </div>
      </main>
    </>
  )
}
